name: HIV_reversion
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8.12
  - snakemake=6.4.1
  - biopython=1.76
  - nextstrain-cli=3.0.3
  - augur=12.0.0
  - auspice=2.23.0
  - matplotlib=3.3.2
  - click=7.1.2